---
- name: Deploy calendar RSVP reminder
  hosts: calendar_hosts
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../secrets.yml"

  roles:
    # - role: base
    # - role: calendar_user
    - role: reminder
